name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.1.0

      - uses: pnpm/action-setup@v4.4.0
        with:
          version: 10.34.5

      - uses: actions/setup-node@v6.5.0
        with:
          node-version: "24.18.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm check

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test
